TesteJAMP/Models/Pessoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TesteJAMP.Models
{
    public class Pessoa
    {
        public string Nome { get; set; }
        public string DataNascimento { get; set; }
        [Key]
        public string Rg { get; set; }
        public string Sexo { get; set; }
        public string Endereco { get; set; }
        
}
}

TesteJAMP/Models/PessoaContextDB2.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using TesteJAMP.Models;

namespace TesteJAMP.Models
{
    public class PessoaContextDB2 : DbContext
    {
        public DbSet<Pessoa> PessoaBO { get; set; }
    }
}

TesteJAMP/Models/RelatorioBO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TesteJAMP.Models;

namespace TesteJAMP.Models
{
    public class RelatorioBO
    {
        public double perc0_9 { get; set; }
        public double perc10_19 { get; set; }
        public double perc20_29 { get; set; }
        public double perc30_39 { get; set; }
        public double perc40 { get; set; }
        public double percMasc { get; set; }
        public double percFem { get; set; }
        public int qntMasc { get; set; }
        public int qntFem { get; set; }
        public int qntPessoas { get; set; }

        public RelatorioBO (List<Pessoa> pessoas)
        {
            perc0_9 = System.Math.Round((double)((pessoas.FindAll(x => GetAge(x.DataNascimento) >= 0 && GetAge(x.DataNascimento) <= 9).Count)) / pessoas.Count * 100,2);
            perc10_19 = System.Math.Round((double)((pessoas.FindAll(x => GetAge(x.DataNascimento) >= 10 && GetAge(x.DataNascimento) <= 19).Count)) / pessoas.Count * 100, 2);
            perc20_29 = System.Math.Round((double)((pessoas.FindAll(x => GetAge(x.DataNascimento) >= 20 && GetAge(x.DataNascimento) <= 29).Count)) / pessoas.Count * 100, 2);
            perc30_39 = System.Math.Round((double)((pessoas.FindAll(x => GetAge(x.DataNascimento) >= 30 && GetAge(x.DataNascimento) <= 39).Count)) / pessoas.Count * 100, 2);
            perc40 = System.Math.Round((double)((pessoas.FindAll(x => GetAge(x.DataNascimento) >= 40).Count)) / pessoas.Count * 100, 2);
            percMasc = System.Math.Round((double)((pessoas.FindAll(x => x.Sexo == "Masculino").Count)) / pessoas.Count * 100, 2);
            percFem = System.Math.Round((double)((pessoas.FindAll(x => x.Sexo == "Feminino").Count)) / pessoas.Count * 100, 2);
            qntMasc = pessoas.FindAll(x => x.Sexo == "Masculino").Count;
            qntFem = pessoas.FindAll(x => x.Sexo == "Feminino").Count;
            qntPessoas = pessoas.Count;
        }

        public static Int32 GetAge(string Birthday)
        {
            //Mussa - Ignorando anos bissextos e aniversário passado.
            DateTime dateOfBirth = DateTime.Parse(Birthday);
            var today = DateTime.Today;

            var age = today.Year - dateOfBirth.Year;

            return age;
        }



    }
}

TesteJAMP/Controllers/CustomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TesteJAMP.Controllers
{
    public class CustomController : Controller
    {
        // GET: Custom
        public ActionResult RGExistente()
        {
            return View();
        }
    }
}

TesteJAMP/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TesteJAMP.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Aplicação teste Mussa para Neppo 2018.";
            
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "João Mussa. Telefone: (34) 99666-9573";

            return View();
        }
    }
}

TesteJAMP/Controllers/PessoaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TesteJAMP.Models;

namespace TesteJAMP.Controllers
{
    public class PessoaController : Controller
    {
        private PessoaContextDB2 db = new PessoaContextDB2();
        

        // GET: Pessoa
        public ActionResult Index()
        {
            return View(db.PessoaBO.ToList());
        }

        // GET: Relatorio
        public ActionResult Relatorio()
        {
            var pessoas = db.PessoaBO.ToList();
            RelatorioBO relatorio = new RelatorioBO(pessoas);
            return View(relatorio);
        }
        
        // GET: Pessoa/Details/5
        public ActionResult Details(string rg)
        {
            if (rg == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pessoa pessoaFound = db.PessoaBO.Find(rg);
            if (pessoaFound == null)
            {
                return HttpNotFound();
            }
            return View(pessoaFound);
        }

        // GET: Pessoa/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pessoa/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Nome,DataNascimento,Rg,Sexo,Endereco")] Pessoa p)
        {
            if (ModelState.IsValid)
            {
                Pessoa pessoaFound = db.PessoaBO.Find(p.Rg);
                if (pessoaFound != null)
                {
                    return RedirectToAction("RGExistente", "Custom");
                }

                db.PessoaBO.Add(p);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(p);
        }

        // GET: Pessoa/Edit/5
        public ActionResult Edit(string rg)
        {
            if (rg == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pessoa pessoaFound = db.PessoaBO.Find(rg);
            if (pessoaFound == null)
            {
                return HttpNotFound();
            }
            return View(pessoaFound);
        }
        

        // POST: Pessoa/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Nome,DataNascimento,Rg,Sexo,Endereco")] Pessoa p)
        {
            if (ModelState.IsValid)
            {
                db.Entry(p).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(p);
        }

        // GET: Pessoa/Delete/5
        public ActionResult Delete(string rg)
        {
            if (rg == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pessoa pessoaFound = db.PessoaBO.Find(rg);
            if (pessoaFound == null)
            {
                return HttpNotFound();
            }
            return View(pessoaFound);
        }

        // POST: Pessoa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string rg)
        {
            Pessoa pessoaFound = db.PessoaBO.Find(rg);
            db.PessoaBO.Remove(pessoaFound);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TesteJAMP/Views/Custom/RGExistente.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Erro</title>

    <script>
        function goBack() {
            window.history.back();
        }
    </script>
    <style>
        button {
            background-color: #e7e7e7;
            color: black;
            border: none;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
        }
    </style>
</head>
<body>
    <h1>Não foi possível adicionar</h1>
    <img src="http://www.stickpng.com/assets/images/5a81af7d9123fa7bcc9b0793.png" alt="Warning" width="400" height="400" />
    <h3>O RG inserido já existe em nosso banco de dados.</h3>
    <br/>
    <button onclick="goBack()">Voltar</button>

</body>
</html>

TesteJAMP/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

TesteJAMP/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

TesteJAMP/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>TESTE MUSSA</h1>
</div>

TesteJAMP/Views/Pessoa/Create.cshtml
@model TesteJAMP.Models.Pessoa

@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Pessoa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control", type = "date", required = "required" } })
                @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rg, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Rg, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Sexo, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.Sexo, new System.Web.Mvc.SelectList(new List<string> { "Feminino", "Masculino" }), new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TesteJAMP/Views/Pessoa/Delete.cshtml
@model TesteJAMP.Models.Pessoa

@{
    ViewBag.Title = "Delete";
}

<h2>Deletar</h2>

<h3>Deseja realmente deletar essa pessoa?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Rg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-danger" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

TesteJAMP/Views/Pessoa/Details.cshtml
@model TesteJAMP.Models.Pessoa

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Rg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { rg = Model.Rg }) |
    @Html.ActionLink("Voltar", "Index")
</p>

TesteJAMP/Views/Pessoa/Edit.cshtml
@model TesteJAMP.Models.Pessoa

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Rg)

    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control", type = "date", required = "required" } })
            @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.Sexo, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.DropDownListFor(model => model.Sexo, new System.Web.Mvc.SelectList(new List<string> { "Feminino", "Masculino" }), new { htmlAttributes = new { @class = "form-control", required = "required" } })
            @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TesteJAMP/Views/Pessoa/Index.cshtml
@model IEnumerable<TesteJAMP.Models.Pessoa>

@{
    ViewBag.Title = "Index";
}






@if (Model.ToList().Count >= 1)
{
    <h2>Lista de Pessoas</h2>

    <p>
        @Html.ActionLink("Cadastrar Pessoa", "Create")
    </p>
    <table class="table">

        <tr>
            <th>
                RG
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                Data de Nascimento
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Rg)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataNascimento)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { rg = item.Rg }) |
                    @Html.ActionLink("Detalhes", "Details", new { rg = item.Rg }) |
                    @Html.ActionLink("Deletar", "Delete", new { rg = item.Rg })
                </td>
            </tr>
        }

    </table>
}
else
{
    <h2>
        Ainda não há pessoas cadastradas.
    </h2>

    <p>
        @Html.ActionLink("Cadastrar Pessoa", "Create")
    </p>
}

TesteJAMP/Views/Pessoa/Relatorio.cshtml
@model TesteJAMP.Models.RelatorioBO

@{
    ViewBag.Title = "Relatorio Pessoas";
}

@if (Model.qntPessoas == 0)
{

    <h2>Ainda não há pessoas cadastradas.</h2>

    <p>
        @Html.ActionLink("Cadastrar Pessoa", "Create")
    </p>
}
else
{

    <h2>Gráfico de Idade</h2>


    <ul class="bar-graph">

        <li class="bar-graph-axis">
            <div class="bar-graph-label">100%</div>
            <div class="bar-graph-label">80%</div>
            <div class="bar-graph-label">60%</div>
            <div class="bar-graph-label">40%</div>
            <div class="bar-graph-label">20%</div>
            <div class="bar-graph-label">0%</div>
        </li>

        <li class="bar secondary" style="height: @Model.perc0_9.ToString().Replace(",",".")%;" title="@Model.perc0_9">
            <div class="percent">@Model.perc0_9<span>%</span></div>
            <div class="description">0 a 9 anos</div>
        </li>

        <li class="bar secondary" style="height: @Model.perc10_19.ToString().Replace(",",".")%;" title="@Model.perc10_19">
            <div class="percent">@Model.perc10_19<span>%</span></div>
            <div class="description">10 a 19 anos</div>
        </li>

        <li class="bar secondary" style="height: @Model.perc20_29.ToString().Replace(",",".")%;" title="@Model.perc20_29">
            <div class="percent">@Model.perc20_29<span>%</span></div>
            <div class="description">20 a 29 anos</div>
        </li>

        <li class="bar secondary" style="height: @Model.perc30_39.ToString().Replace(",",".")%;" title="@Model.perc30_39">
            <div class="percent">@Model.perc30_39<span>%</span></div>
            <div class="description">30 a 39 anos</div>
        </li>

        <li class="bar secondary" style="height: @Model.perc40.ToString().Replace(",",".")%;" title="@Model.perc40">
            <div class="percent">@Model.perc40<span>%</span></div>
            <div class="description">Mais de 40 anos</div>
        </li>

    </ul>


    <br />
    <br />


    <h2>Proporção Sexo</h2>

    <br />

    <div class="progress">
        <div title="Masculino (@Model.qntMasc.ToString())" class="progress-bar progress-bar-info" role="progressbar" style="width:@Model.percMasc.ToString().Replace(",",".")%">
            Masculino (@Model.qntMasc.ToString())
        </div>
        <div title="Feminino (@Model.qntFem.ToString())" class="progress-bar progress-bar-danger" role="progressbar" style="width:@Model.percFem.ToString().Replace(",",".")%">
            Feminino (@Model.qntFem.ToString())
        </div>
    </div>
}

TesteJAMP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Teste JAMP</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Teste JAMP", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Pessoas", "Index", "Pessoa")</li>
                    <li>@Html.ActionLink("Relatorio", "Relatorio", "Pessoa")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Página feita por João Mussa</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>